import type {
  Patient,
  InboxItem,
  Appointment,
  AgentActivity,
  AutoCompletedItem,
} from './types';

export const patients: Patient[] = [
  {
    id: 'p1',
    name: 'Maria Lopez',
    dob: '1978-03-14',
    mrn: '100234',
    insurance: 'BCBS',
    insuranceStatus: 'Active',
    visitReason: 'Neurology follow-up',
  },
  {
    id: 'p2',
    name: 'James Chen',
    dob: '1965-08-22',
    mrn: '100235',
    insurance: 'Aetna',
    insuranceStatus: 'Active',
    visitReason: 'New patient evaluation',
  },
  {
    id: 'p3',
    name: 'Sarah Okonkwo',
    dob: '1990-11-05',
    mrn: '100236',
    insurance: 'United',
    insuranceStatus: 'Active',
    visitReason: 'EEG review',
  },
  {
    id: 'p4',
    name: 'Robert Patel',
    dob: '1952-06-30',
    mrn: '100237',
    insurance: 'Medicare',
    insuranceStatus: 'Active',
    visitReason: 'EMG consult',
  },
  {
    id: 'p5',
    name: 'Diana Walsh',
    dob: '1983-01-18',
    mrn: '100238',
    insurance: 'Cigna',
    insuranceStatus: 'Pending',
    visitReason: 'Headache follow-up',
  },
  {
    id: 'p6',
    name: 'Thomas Nguyen',
    dob: '1971-09-09',
    mrn: '100239',
    insurance: 'BCBS',
    insuranceStatus: 'Active',
    visitReason: 'Botox injection',
  },
];

export const inboxItems: InboxItem[] = [
  {
    id: 'i1',
    type: 'Eligibility Re-verification',
    category: 'eligibility',
    patientId: 'p1',
    patientName: 'Maria Lopez',
    title: 'Eligibility re-verified — BCBS Active',
    summary: 'Coverage confirmed through 12/31/2026. Copay $40, deductible $500 remaining.',
    agentName: 'Eligibility Agent',
    confidence: 0.97,
    status: 'pending',
    priority: 'high',
    createdAt: '2026-05-17T07:02:00Z',
    slaMinutes: 60,
    reasoning:
      'Real-time payer query returned active coverage. Member ID matched on file. No plan changes detected since last visit. Copay and deductible pulled from current benefit period.',
    sources: ['BCBS Eligibility API', 'Patient Demographics — MRN 100234', 'Plan Benefits Cache'],
  },
  {
    id: 'i2',
    type: 'Eligibility Re-verification',
    category: 'eligibility',
    patientId: 'p2',
    patientName: 'James Chen',
    title: 'Eligibility re-verified — Aetna Active',
    summary: 'Active PPO plan. Referral required for specialist visits. Out-of-pocket max met.',
    agentName: 'Eligibility Agent',
    confidence: 0.94,
    status: 'pending',
    priority: 'high',
    createdAt: '2026-05-17T07:05:00Z',
    slaMinutes: 60,
    reasoning:
      'Aetna returned active status. PPO plan requires PCP referral on file — referral #REF-8821 verified. Out-of-pocket max of $3,500 met as of April billing cycle.',
    sources: ['Aetna Eligibility API', 'Referral Registry', 'Patient Demographics — MRN 100235'],
  },
  {
    id: 'i3',
    type: 'Eligibility Re-verification',
    category: 'eligibility',
    patientId: 'p3',
    patientName: 'Sarah Okonkwo',
    title: 'Eligibility re-verified — United Active',
    summary: 'HMO plan active. In-network confirmed. $20 copay applies.',
    agentName: 'Eligibility Agent',
    confidence: 0.91,
    status: 'pending',
    priority: 'medium',
    createdAt: '2026-05-17T07:08:00Z',
    slaMinutes: 120,
    reasoning:
      'United Healthcare confirmed active HMO enrollment. Provider NPI 1234567890 is in-network. Standard neurology specialist copay of $20 applies per plan schedule.',
    sources: ['United HC Eligibility API', 'Provider NPI Registry', 'Plan Fee Schedule'],
  },
  {
    id: 'i4',
    type: 'Eligibility Re-verification',
    category: 'eligibility',
    patientId: 'p4',
    patientName: 'Robert Patel',
    title: 'Eligibility re-verified — Medicare Part B Active',
    summary: 'Medicare Part B active. 80/20 cost-share applies. Secondary Medigap on file.',
    agentName: 'Eligibility Agent',
    confidence: 0.98,
    status: 'pending',
    priority: 'high',
    createdAt: '2026-05-17T07:10:00Z',
    slaMinutes: 60,
    reasoning:
      'Medicare eligibility confirmed via HETS real-time query. Part B covers EMG services under CPT 95911. Medigap Plan G covers the 20% patient liability. No prior auth required for EMG under Medicare.',
    sources: ['Medicare HETS API', 'Medigap Secondary Verification', 'LCD for EMG Services'],
  },
  {
    id: 'i5',
    type: 'Scheduling Request',
    category: 'message',
    patientId: 'p1',
    patientName: 'Maria Lopez',
    title: 'Patient requesting earlier appointment',
    summary: 'Maria asks if her June 3 follow-up can move to late May due to travel plans.',
    agentName: 'Scheduling Agent',
    confidence: 0.88,
    status: 'pending',
    priority: 'medium',
    createdAt: '2026-05-17T08:15:00Z',
    slaMinutes: 480,
    reasoning:
      'Patient portal message received at 8:14 AM. Parsed intent: reschedule request. Detected travel conflict window June 1–10. Found available slot May 29 at 2:30 PM with Dr. Reyes. Drafted reply pending approval.',
    sources: ['Patient Portal Message', 'Schedule Availability API', 'Dr. Reyes Calendar'],
  },
  {
    id: 'i6',
    type: 'Billing Question',
    category: 'message',
    patientId: 'p2',
    patientName: 'James Chen',
    title: 'Patient billing inquiry — balance confusion',
    summary: 'James disputes a $180 balance; believes insurance should have covered the visit.',
    agentName: 'Billing Agent',
    confidence: 0.72,
    status: 'pending',
    priority: 'medium',
    createdAt: '2026-05-17T08:40:00Z',
    slaMinutes: 240,
    reasoning:
      'Balance of $180 corresponds to Feb 12 visit. Claim paid at in-network rate but patient applied $180 toward deductible. Patient may not have met deductible at time of service. Suggest billing team review with patient. Confidence moderate due to claim complexity.',
    sources: ['Patient Portal Message', 'Claim #CLM-29382', 'EOB Feb 2026'],
  },
  {
    id: 'i7',
    type: 'Clinical Question',
    category: 'message',
    patientId: 'p5',
    patientName: 'Diana Walsh',
    title: 'Clinical question routed to provider',
    summary: 'Diana asks if her new medication (topiramate) can be taken with ibuprofen.',
    agentName: 'Triage Agent',
    confidence: 0.95,
    status: 'pending',
    priority: 'high',
    createdAt: '2026-05-17T09:05:00Z',
    slaMinutes: 120,
    reasoning:
      'Message classified as clinical question requiring provider response. Drug interaction check: topiramate + ibuprofen — no major interaction found in DrugBank, but ibuprofen may worsen kidney stone risk associated with topiramate. Routed to Dr. Reyes for review. Do not auto-respond.',
    sources: ['Patient Portal Message', 'DrugBank Interaction API', 'Patient Medication List'],
  },
  {
    id: 'i8',
    type: 'Prior Auth Approved',
    category: 'prior-auth',
    patientId: 'p3',
    patientName: 'Sarah Okonkwo',
    title: 'Prior auth approved — EEG study',
    summary: 'United approved PA for routine EEG (CPT 95816). Auth #UA-774421, valid 90 days.',
    agentName: 'Prior Auth Agent',
    confidence: 0.99,
    status: 'pending',
    priority: 'low',
    createdAt: '2026-05-17T06:50:00Z',
    slaMinutes: 30,
    reasoning:
      'Payer returned approval decision via 278 transaction. Auth number confirmed valid. Expiration date 90 days from today. All required clinical criteria met per United neurology policy.',
    sources: ['United HC 278 Response', 'PA Request #PAR-2241', 'Clinical Criteria Checklist'],
  },
  {
    id: 'i9',
    type: 'Prior Auth Escalation',
    category: 'prior-auth',
    patientId: 'p6',
    patientName: 'Thomas Nguyen',
    title: 'Botox PA — peer-to-peer escalation needed',
    summary: 'BCBS denied initial PA for Botox (migraine). Peer-to-peer call required by May 20.',
    agentName: 'Prior Auth Agent',
    confidence: 0.83,
    status: 'pending',
    priority: 'high',
    createdAt: '2026-05-17T07:45:00Z',
    slaMinutes: 180,
    reasoning:
      'BCBS issued technical denial citing insufficient documentation of prior preventive therapy failures. Clinical notes support 4+ prior medication trials. Peer-to-peer appeal has 60% approval rate historically for this denial type. Deadline May 20 at 5 PM.',
    sources: ['BCBS Denial Letter #DN-8833', 'Clinical Notes — 3 visits', 'PA Appeal Policy'],
  },
  {
    id: 'i10',
    type: 'Inbound Fax — Referral',
    category: 'document',
    patientId: 'p2',
    patientName: 'James Chen',
    title: 'Inbound referral fax from Primary Care',
    summary: 'Referral from Dr. Amara Osei (PCP) for new patient neuro eval. Attached: 3 pages.',
    agentName: 'Document Agent',
    confidence: 0.89,
    status: 'pending',
    priority: 'medium',
    createdAt: '2026-05-17T09:20:00Z',
    slaMinutes: 240,
    reasoning:
      'Fax classified as referral based on header text, sender NPI, and document structure. Sender Dr. Amara Osei NPI 9876543210 matched to known PCP in network. Patient matched by name and DOB. Suggest filing to James Chen chart and scheduling new patient appointment.',
    sources: ['Fax Queue #FX-0312', 'NPI Registry', 'Patient Match — MRN 100235'],
  },
  {
    id: 'i11',
    type: 'Inbound Fax — Lab Result',
    category: 'document',
    patientId: 'p4',
    patientName: 'Robert Patel',
    title: 'Lab result — nerve conduction study report',
    summary: 'Inbound NCS report from Quest. Abnormal findings: reduced conduction velocity L ulnar.',
    agentName: 'Document Agent',
    confidence: 0.93,
    status: 'pending',
    priority: 'high',
    createdAt: '2026-05-17T09:35:00Z',
    slaMinutes: 120,
    reasoning:
      'Document classified as lab result (NCS report). Flagged as abnormal due to reduced conduction velocity noted in report text. Matched to Robert Patel by MRN on fax coversheet. Provider review required before filing. Abnormal results require clinical acknowledgment per policy.',
    sources: ['Fax Queue #FX-0318', 'Quest Diagnostics', 'Patient Match — MRN 100237'],
  },
  {
    id: 'i12',
    type: 'Coding Review',
    category: 'coding',
    patientId: 'p1',
    patientName: 'Maria Lopez',
    title: 'Coding suggestion — May 16 encounter',
    summary: 'Proposed: 99214 + G2211 + 93000. ICD: G43.909, R51.9. Est. reimbursement $312.',
    agentName: 'Coding Agent',
    confidence: 0.87,
    status: 'pending',
    priority: 'medium',
    createdAt: '2026-05-17T10:00:00Z',
    slaMinutes: 360,
    reasoning:
      'Encounter note supports 99214 (moderate complexity: 2 chronic conditions, new prescription). G2211 applicable as longitudinal care add-on. ECG performed during visit supports 93000. Diagnoses extracted from assessment section. Estimate based on current BCBS fee schedule.',
    sources: ['Encounter Note — May 16', 'BCBS Fee Schedule 2026', 'CMS CPT Guidelines'],
  },
  {
    id: 'i13',
    type: 'Coding Review',
    category: 'coding',
    patientId: 'p3',
    patientName: 'Sarah Okonkwo',
    title: 'Coding suggestion — EEG interpretation encounter',
    summary: 'Proposed: 95816 + 99213. ICD: G40.909, R56.9. Est. reimbursement $228.',
    agentName: 'Coding Agent',
    confidence: 0.91,
    status: 'pending',
    priority: 'medium',
    createdAt: '2026-05-17T10:15:00Z',
    slaMinutes: 360,
    reasoning:
      'EEG interpretation (95816) supported by signed reading in note. E&M 99213 separately billable for in-person discussion of results. Epilepsy (G40.909) and seizure (R56.9) diagnoses confirmed in assessment. Unbundling rules verified — no NCCI edits apply.',
    sources: ['Encounter Note — EEG Review', 'NCCI Edits Database', 'United Fee Schedule 2026'],
  },
  {
    id: 'i14',
    type: 'No-Show Risk Flag',
    category: 'no-show',
    patientId: 'p5',
    patientName: 'Diana Walsh',
    title: 'High no-show risk — tomorrow 10:00 AM',
    summary: 'Diana has 2 prior no-shows. No confirmation received. Risk score: 87%. Consider outreach.',
    agentName: 'Scheduling Agent',
    confidence: 0.87,
    status: 'pending',
    priority: 'high',
    createdAt: '2026-05-17T11:00:00Z',
    slaMinutes: 60,
    reasoning:
      'No-show risk model flagged this appointment. Factors: 2 historical no-shows (last 6 months), appointment not yet confirmed via text/email, Cigna insurance in Pending status (financial barrier signal), appointment is first slot after lunch (historically higher no-show rate). Recommend SMS/phone outreach today.',
    sources: ['Appointment History', 'No-Show Risk Model v2.1', 'Patient Contact Log'],
  },
];

export const todaysSchedule: Appointment[] = [
  {
    id: 'a1',
    patientId: 'p2',
    patientName: 'James Chen',
    time: '08:00',
    duration: 60,
    visitType: 'New Patient Evaluation',
    provider: 'Dr. Reyes',
    status: 'checked-in',
    noShowRisk: 'low',
    room: 'Exam 2',
  },
  {
    id: 'a2',
    patientId: 'p1',
    patientName: 'Maria Lopez',
    time: '09:00',
    duration: 30,
    visitType: 'Neurology Follow-up',
    provider: 'Dr. Reyes',
    status: 'confirmed',
    noShowRisk: 'low',
    room: 'Exam 1',
  },
  {
    id: 'a3',
    patientId: 'p3',
    patientName: 'Sarah Okonkwo',
    time: '10:00',
    duration: 45,
    visitType: 'EEG Review',
    provider: 'Dr. Reyes',
    status: 'in-room',
    noShowRisk: 'low',
    room: 'EEG Suite',
  },
  {
    id: 'a4',
    patientId: 'p4',
    patientName: 'Robert Patel',
    time: '11:00',
    duration: 60,
    visitType: 'EMG Consult',
    provider: 'Dr. Reyes',
    status: 'confirmed',
    noShowRisk: 'medium',
    room: 'Exam 3',
  },
  {
    id: 'a5',
    patientId: 'p5',
    patientName: 'Diana Walsh',
    time: '12:30',
    duration: 30,
    visitType: 'Headache Follow-up',
    provider: 'Dr. Reyes',
    status: 'no-show',
    noShowRisk: 'high',
  },
  {
    id: 'a6',
    patientId: 'p6',
    patientName: 'Thomas Nguyen',
    time: '13:30',
    duration: 30,
    visitType: 'Botox Injection',
    provider: 'Dr. Reyes',
    status: 'scheduled',
    noShowRisk: 'low',
  },
  {
    id: 'a7',
    patientId: 'p1',
    patientName: 'Maria Lopez',
    time: '14:30',
    duration: 30,
    visitType: 'Med Check',
    provider: 'Dr. Reyes',
    status: 'confirmed',
    noShowRisk: 'low',
  },
  {
    id: 'a8',
    patientId: 'p2',
    patientName: 'James Chen',
    time: '16:00',
    duration: 30,
    visitType: 'Lab Review',
    provider: 'Dr. Reyes',
    status: 'scheduled',
    noShowRisk: 'medium',
  },
];

export const agentActivity: AgentActivity[] = [
  {
    id: 'aa1',
    agentName: 'Eligibility Agent',
    action: 'Re-verified coverage for 6 patients ahead of today\'s schedule',
    patientName: 'Batch (6 patients)',
    timestamp: '2026-05-17T07:12:00Z',
    outcome: 'success',
  },
  {
    id: 'aa2',
    agentName: 'Scheduling Agent',
    action: 'Sent appointment reminders via SMS',
    patientName: 'Batch (8 patients)',
    timestamp: '2026-05-17T07:00:00Z',
    outcome: 'success',
  },
  {
    id: 'aa3',
    agentName: 'Document Agent',
    action: 'Classified 2 inbound faxes and matched to patient charts',
    patientName: 'James Chen, Robert Patel',
    timestamp: '2026-05-17T09:38:00Z',
    outcome: 'pending',
  },
  {
    id: 'aa4',
    agentName: 'Coding Agent',
    action: 'Proposed CPT/ICD codes for 2 yesterday encounters',
    patientName: 'Maria Lopez, Sarah Okonkwo',
    timestamp: '2026-05-17T10:20:00Z',
    outcome: 'pending',
  },
  {
    id: 'aa5',
    agentName: 'Prior Auth Agent',
    action: 'Retrieved PA approval for EEG study',
    patientName: 'Sarah Okonkwo',
    timestamp: '2026-05-17T06:52:00Z',
    outcome: 'success',
  },
  {
    id: 'aa6',
    agentName: 'Prior Auth Agent',
    action: 'Escalated Botox PA denial — peer-to-peer required',
    patientName: 'Thomas Nguyen',
    timestamp: '2026-05-17T07:48:00Z',
    outcome: 'escalated',
  },
  {
    id: 'aa7',
    agentName: 'Triage Agent',
    action: 'Classified patient messages and routed to appropriate queues',
    patientName: 'Maria Lopez, James Chen, Diana Walsh',
    timestamp: '2026-05-17T09:10:00Z',
    outcome: 'success',
  },
  {
    id: 'aa8',
    agentName: 'Scheduling Agent',
    action: 'Flagged high no-show risk for tomorrow appointment',
    patientName: 'Diana Walsh',
    timestamp: '2026-05-17T11:02:00Z',
    outcome: 'escalated',
  },
  {
    id: 'aa9',
    agentName: 'Billing Agent',
    action: 'Reviewed patient billing inquiry and pulled relevant claims',
    patientName: 'James Chen',
    timestamp: '2026-05-17T08:42:00Z',
    outcome: 'pending',
  },
  {
    id: 'aa10',
    agentName: 'Eligibility Agent',
    action: 'Detected Cigna insurance status change to Pending for Diana Walsh',
    patientName: 'Diana Walsh',
    timestamp: '2026-05-17T07:55:00Z',
    outcome: 'escalated',
  },
];

export const autoCompletedItems: AutoCompletedItem[] = [
  {
    id: 'ac1',
    agentName: 'Eligibility Agent',
    description: 'Verified active Medicare coverage for Robert Patel — no changes detected',
    patientName: 'Robert Patel',
    timestamp: '2026-05-17T07:10:00Z',
    category: 'eligibility',
  },
  {
    id: 'ac2',
    agentName: 'Scheduling Agent',
    description: 'Sent appointment reminder to Thomas Nguyen via SMS — delivered',
    patientName: 'Thomas Nguyen',
    timestamp: '2026-05-17T07:00:00Z',
    category: 'scheduling',
  },
  {
    id: 'ac3',
    agentName: 'Document Agent',
    description: 'Filed signed patient consent forms to Maria Lopez chart',
    patientName: 'Maria Lopez',
    timestamp: '2026-05-17T08:30:00Z',
    category: 'document',
  },
  {
    id: 'ac4',
    agentName: 'Prior Auth Agent',
    description: 'Re-submitted expired PA request for Sarah Okonkwo EEG — approved',
    patientName: 'Sarah Okonkwo',
    timestamp: '2026-05-17T06:55:00Z',
    category: 'prior-auth',
  },
  {
    id: 'ac5',
    agentName: 'Scheduling Agent',
    description: 'Auto-confirmed James Chen appointment after he responded YES to SMS',
    patientName: 'James Chen',
    timestamp: '2026-05-17T06:45:00Z',
    category: 'scheduling',
  },
  {
    id: 'ac6',
    agentName: 'Coding Agent',
    description: 'Submitted clean claims for 4 encounters from May 15 with no edits needed',
    patientName: 'Batch (4 patients)',
    timestamp: '2026-05-17T09:00:00Z',
    category: 'coding',
  },
];
